# Generated by Django 5.0.1 on 2024-04-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmxMaster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='fixture_group',
        ),
    ]
