# Generated by Django 5.0.1 on 2024-04-28 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmxMaster', '0002_remove_fixture_fixture_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mixer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
                ('mixerType', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GroupLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmxMaster.fixture')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmxMaster.group')),
            ],
        ),
        migrations.CreateModel(
            name='MixerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageID', models.IntegerField(default=0)),
                ('mixer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmxMaster.mixer')),
            ],
        ),
        migrations.CreateModel(
            name='MixerFader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('isTouched', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('assignedID', models.IntegerField(default=0)),
                ('assignedType', models.IntegerField(default=0)),
                ('mixerPage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmxMaster.mixerpage')),
            ],
        ),
        migrations.CreateModel(
            name='MixerButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('isPressed', models.CharField(max_length=200)),
                ('assignedID', models.IntegerField(default=0)),
                ('assignedType', models.IntegerField(default=0)),
                ('mixerPage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmxMaster.mixerpage')),
            ],
        ),
    ]
