# Generated by Django 5.0.4 on 2024-05-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmxMaster', '0007_project_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='assigned_setup_fader',
            field=models.IntegerField(default=1),
        ),
    ]
