# Generated by Django 5.0.4 on 2024-05-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmxMaster', '0008_fixture_assigned_setup_fader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='assigned_setup_fader',
        ),
    ]
