# Generated by Django 5.0.4 on 2024-05-30 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmxMaster', '0010_project_channels_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='selected_Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dmxMaster.fixture')),
                ('project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dmxMaster.project')),
            ],
        ),
        migrations.CreateModel(
            name='selected_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dmxMaster.fixture')),
                ('project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dmxMaster.project')),
            ],
        ),
    ]
