# Generated by Django 5.0.4 on 2024-05-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmxMaster', '0012_remove_selected_group_fixture_selected_group_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='selected_Fixture',
            new_name='SelectedFixture',
        ),
        migrations.RenameModel(
            old_name='selected_Group',
            new_name='SelectedGroup',
        ),
    ]
