# Generated by Django 5.0.1 on 2024-06-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmxMaster', '0013_rename_selected_fixture_selectedfixture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='selectedgroup',
            name='project',
        ),
        migrations.AddField(
            model_name='fixture',
            name='selected',
            field=models.CharField(default='false', max_length=200),
        ),
        migrations.AddField(
            model_name='group',
            name='selected',
            field=models.CharField(default='false', max_length=200),
        ),
        migrations.DeleteModel(
            name='SelectedFixture',
        ),
        migrations.DeleteModel(
            name='SelectedGroup',
        ),
    ]
